"""A local reference consumer for checking the contract before Android adoption."""
from html import escape
from .contracts import validate_bundle, canonical


def render(packs):
    validate_bundle(packs)
    data,model,story=packs['data'],packs['model'],packs['story']
    encoded=canonical(packs).decode().replace('<','\\u003c').replace('>','\\u003e').replace('&','\\u0026')
    return '''<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Atlas · Stock no es demanda</title>
<style>
body{margin:0;background:#f7f3e9;color:#172c30;font:18px/1.6 system-ui,sans-serif}main{max-width:980px;margin:auto;padding:40px 24px}header{border-bottom:2px solid #1e6860;padding-bottom:32px}h1{font-family:Georgia,serif;line-height:1.15;font-size:clamp(34px,6vw,64px);max-width:850px}h2{font:32px Georgia,serif}.eyebrow{letter-spacing:.14em;font-size:12px;font-weight:700}.badge{display:inline-block;background:#f2d785;padding:6px 14px;border-radius:4px}section{margin:42px 0}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}.card,details{padding:20px;border:1px solid #bec9bd;background:#fffdf6;border-radius:12px}.metric{font-size:32px;color:#206b60}label{display:block;margin:16px 0}input{width:min(100%,600px)}button{background:#206b60;color:white;border:0;padding:12px;border-radius:6px}select{font:inherit;padding:8px}svg{width:100%;height:auto}.muted{color:#526566;font-size:14px}summary{cursor:pointer}table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:left;border-bottom:1px solid #ddd;padding:8px}:focus-visible{outline:3px solid #aa6200;outline-offset:4px}output{display:block;font-size:24px}a{color:#206b60}
</style><main><header><p class="eyebrow">MEDALLIO → ATLAS · MUSEO-LAB</p><p class="badge">'''+escape(data['label'])+'''</p><h1>'''+escape(story['question'])+'''</h1><p>Una exploración de saldos, ritmos y supuestos. Datos → evidencia → modelo → interpretación.</p><a href="#lab">Ir al experimento ↓</a></header>
<section><h2>01 · Observa</h2><label>Proyecto <select id="project"></select></label><div class="cards" id="cards"></div><h3>Las ventas cuentan una historia que el saldo no cuenta</h3><div id="chart"></div><p class="muted" id="source"></p><details><summary>Ver datos y metodología</summary><div id="table"></div></details></section>
<section><h2>02 · Interpreta la evidencia</h2><p id="finding"></p><p>Una diferencia descriptiva no identifica su causa. Composición, estacionalidad o demanda son hipótesis por investigar.</p></section>
<section><h2>03 · Abre el modelo</h2><div class="card"><h3>Media móvil de tres meses</h3><p>'''+escape(model['explanation'])+'''</p><p id="metric"></p><details><summary>Cómo se evaluó y qué no permite concluir</summary><p>'''+escape(model['validation'])+'''</p><p>'''+escape(model['uncertainty']['explanation'])+'''</p><p>'''+escape(' '.join(model['limitations']))+'''</p></details></div></section>
<section id="lab"><h2>04 · Cambia un supuesto</h2><p>¿Y si el próximo ritmo fuera menor o mayor? El multiplicador es tu supuesto: no representa el efecto estimado del precio.</p><label for="multiplier">Multiplicador del ritmo <span id="factor"></span></label><input id="multiplier" type="range" min="0.5" max="1.5" value="1" step="0.05"><output id="result" aria-live="polite"></output><p id="explain"></p><button id="reset">Restablecer escenario original</button></section>
<section><h2>05 · Del resultado a la decisión</h2><div class="cards"><div class="card"><h3>Qué aprendimos</h3><p>'''+escape(story['what_we_learned'])+'''</p></div><div class="card"><h3>Qué no sabemos</h3><p>'''+escape(story['what_we_do_not_know'])+'''</p></div><div class="card"><h3>Qué probar después</h3><p>'''+escape(story['next_test'])+'''</p></div></div><p>Decisión: requiere revisión humana. Resultado comercial: todavía no observado.</p><h3>Wisdom Card · Stock no es demanda</h3><p>Compara ritmo, composición y exposición. Esta es una enseñanza educativa, no una política validada.</p></section><footer class="muted">Consumidor de referencia offline. Sin servicios externos, entrenamiento en el dispositivo ni datos privados en la demostración.</footer></main>
<script id="packs" type="application/json">'''+encoded+'''</script><script>
const p=JSON.parse(document.getElementById('packs').textContent),$=id=>document.getElementById(id);
const projects=p.model.results.map(r=>r.project);
projects.forEach(x=>{const o=document.createElement('option');o.textContent=x;o.value=x;$('project').append(o)});
const fmt=x=>new Intl.NumberFormat('es-PE',{maximumFractionDigits:2}).format(x);
function experiment(){const r=p.model.results.find(r=>r.project===$('project').value),m=Number($('multiplier').value),v=Math.min(r.stock,r.prediction*m);$('factor').textContent=fmt(m)+'×';$('result').textContent=fmt(v)+' unidades para el siguiente mes';$('explain').textContent='Original: '+fmt(r.prediction)+' · Cambio: '+fmt(v-r.prediction)+' · Stock límite: '+fmt(r.stock)+'. Escenario condicionado; no certeza.'}
function refresh(){const project=$('project').value,rows=p.data.rows.filter(r=>r.project===project).sort((a,b)=>a.period.localeCompare(b.period));$('cards').replaceChildren();p.data.indicators.filter(i=>i.id.startsWith(project+'-')).forEach(i=>{const c=document.createElement('div');c.className='card';const name=document.createElement('div');name.textContent=i.name;const v=document.createElement('div');v.className='metric';v.textContent=fmt(i.value);const u=document.createElement('div');u.textContent=i.unit;c.append(name,v,u);$('cards').append(c)});
$('finding').textContent=p.story.findings.find(f=>f.id===project+'-finding').statement;
$('source').textContent=p.data.provenance.source+' · '+rows[0].period+' a '+rows.at(-1).period+' · actualizado '+p.data.provenance.generated_at+' · '+p.data.provenance.transformation;
const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 800 250');svg.setAttribute('role','img');svg.setAttribute('aria-label','Ventas mensuales en unidades. Datos completos en la tabla siguiente.');const max=Math.max(1,...rows.map(r=>r.sales)),w=720/rows.length;rows.forEach((r,i)=>{const rect=document.createElementNS(ns,'rect');rect.setAttribute('x',40+i*w);rect.setAttribute('y',200-r.sales/max*150);rect.setAttribute('width',w*.65);rect.setAttribute('height',r.sales/max*150);rect.setAttribute('fill','#206b60');svg.append(rect);for(const [text,y] of [[fmt(r.sales),190-r.sales/max*150],[r.period.slice(5,7),224]]){const t=document.createElementNS(ns,'text');t.setAttribute('x',40+i*w);t.setAttribute('y',y);t.setAttribute('font-size','14');t.textContent=text;svg.append(t)}});$('chart').replaceChildren(svg);
const table=document.createElement('table');const head=document.createElement('tr');['Mes','Stock inicial','Ventas','Stock final'].forEach(t=>{const th=document.createElement('th');th.textContent=t;head.append(th)});table.append(head);rows.forEach(r=>{const tr=document.createElement('tr');[r.period,r.stock_open,r.sales,r.stock_close].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});table.append(tr)});$('table').replaceChildren(table);const metric=p.model.metrics[0];$('metric').textContent='MAE: '+fmt(metric.value)+' '+metric.unit+' sobre '+metric.n+' casos de evaluación temporal. '+metric.interpretation;experiment()}
$('project').addEventListener('change',refresh);$('multiplier').addEventListener('input',experiment);$('reset').addEventListener('click',()=>{$('multiplier').value=1;experiment()});refresh();
</script></html>'''
